using MetricRecordModel;

namespace SpawnMetricsStorage.Models.ProjectName;

public sealed class IsValidProjectNameAttribute() : StringLengthValidationAttributeBase(ProjectNameConstants.MinProjectNameLength, ProjectNameConstants.MaxProjectNameLength);