namespace MetricRecordModel;

public sealed class IsValidMetricNameAttribute() : StringLengthValidationAttributeBase(MetricRecordConstants.MinMetricNameLength, MetricRecordConstants.MaxMetricNameLength);